# Generated by Django 2.0 on 2022-12-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='numEscanos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Seats'),
        ),
        migrations.AddField(
            model_name='voting',
            name='tipo',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONT', 'DHONT'), ('IMPERIALI', 'IMPERIALI')], default='IMPERIALI', max_length=20, verbose_name='Count method'),
        ),
    ]
