# Generated by Django 2.0 on 2022-12-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20221210_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='tipo',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONT', 'DHONT'), ('IMPERIALI', 'IMPERIALI'), ('IMPERIALIBORDA', 'IMPERIALIBORDA'), ('DHONTBORDA', 'DHONTBORDA')], default='IMPERIALI', max_length=20, verbose_name='Count method'),
        ),
    ]
